name: Send Email Notification

on:
  push:
    branches:
      - master

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: rccline/action-send-mail@v1.3.0
        env:
          FROM: github-actions@github.com
          TO: 'rccline@fastmail.fm'
     
