name: Email Notification

on:
  push:
    branches:
      - master

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: actions/email@v2
        with:
          subject: 'GitHub Activity'
          body: |
            ${{ github.actor }} pushed ${{ github.event.commits.length }} commits.

            ${{ toJson(github.event.commits) }}
          to:
            - rccline@fastmail.fm 
